apiVersion: v1
kind: Service
metadata:
    name: app-service
spec:
    ports:
        - protocol: TCP 
          port: 80
          targetPort: 5000 
    selector: 
        labels:
            app: demo-python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deployment
    labels:
        app: demo-python-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: demo-python-app
    template:  
        metadata:
            labels:
                app: demo-python-app
        spec:
            containers:
            - name: python-app
              image: <+artifact.image>
              ports:
                - containerPort: 5000 
            

